// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEb07M53RWwZKNSgx3ZJQGsqVQTPHpV-A',
    appId: '1:33829087398:web:afa2ae987be9681f122c67',
    messagingSenderId: '33829087398',
    projectId: 'callendersann',
    authDomain: 'callendersann.firebaseapp.com',
    storageBucket: 'callendersann.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx0b3v6gzio4UUZipjL8MT7HdGiBfnCq8',
    appId: '1:33829087398:android:7da2ec3f56962179122c67',
    messagingSenderId: '33829087398',
    projectId: 'callendersann',
    storageBucket: 'callendersann.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAipDYY_tNhumZrivxpUF3a87gTDkjewPs',
    appId: '1:33829087398:ios:0296a92644ec2c3c122c67',
    messagingSenderId: '33829087398',
    projectId: 'callendersann',
    storageBucket: 'callendersann.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAipDYY_tNhumZrivxpUF3a87gTDkjewPs',
    appId: '1:33829087398:ios:0296a92644ec2c3c122c67',
    messagingSenderId: '33829087398',
    projectId: 'callendersann',
    storageBucket: 'callendersann.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEb07M53RWwZKNSgx3ZJQGsqVQTPHpV-A',
    appId: '1:33829087398:web:b6eccb4e2f3b92c8122c67',
    messagingSenderId: '33829087398',
    projectId: 'callendersann',
    authDomain: 'callendersann.firebaseapp.com',
    storageBucket: 'callendersann.firebasestorage.app',
  );
}
